### ISSUE TITLE
Truly "header only" version

### ISSUE THREAD

**Issue by dbeckerAC** [ZigRazor/CXXGraph#209] opened 2022-08-01 17:19 UTC
**Is your feature request related to a problem? Please describe.**
I want to use the code/lib as header only lib as in **no** dependencies or building operations.

**Describe the solution you'd like**
In the `CMakeLists.txt` file there is no option to deactivate the `test_exe` target which would be compiled and link to various dependencies when I use `add_subdirectory` in my CMake. 
I could just skip CMake and explicitly inclide all required headers. (Only including `CXXGraph.hpp` won't work since `CXXGraphConfig.h` isn't available without CMake.)
But then I run into the only dependency that is required for simple graph operations: zlib, right? And this is just used for compressed files.  
Maybe it is possible to introduce a flag/define that skips zlib.

**Comment by ZigRazor** [comment] 2022-08-02 05:59
Thank you for your feedback.
All you had described in the issue is correct, and is a great enhancement.
I think that all the solution you had ilustrated in the issue can be applied.
So for thi issue we can proceed with this step:

1. Option to activate `test_exe` ( I think is better Deativated by default )
2. Search for Zlib only if defined the necessity to compress/decompress files
3. Try to eliminate `CXXGraphConfig.h` file. 
4. Manage the `make install` in the right manner

**Comment by dbeckerAC** [comment] 2022-08-02 11:18
May I ask what the reason for the sha512 hash is here?
https://github.com/ZigRazor/CXXGraph/blob/4f2b8c315044e86f6738d143fbd7f661303ba9a3/include/Node/Node.hpp#L62  

This introduces the openssl dependency for nodes.

**Comment by ZigRazor** [comment] 2022-08-05 13:38
I think this could be resolved in another issue.
Please open a issue for this comment.

**Comment by amerinor01** [comment] 2022-10-04 21:39
Hi,

Until now I'm already implement the steps 1 and 2.

For the 3 step I was thinking that. In order to do the step 3 I find something that maybe works. see [Cmake project definition](https://riptutorial.com/cmake/example/32603/using-cmake-to-define-the-version-number-for-cplusplus-usage), but instead of use any other config file, use CXXGraph.h as the .in for the Cmake, so create a release would be simpler as just run the Cmake.

For the last step I didn't understand you very well what you mean with "Manage the make install in the right manner". Can you gimme more explanation please?

**Comment by ZigRazor** [comment] 2022-10-05 08:07
Hi @amerinor01,

For the third step, I think the better choice is to copy the contents of the .in file into the CXXGraph.hpp file.

For the fourth step, the make install command of Cmake should install all the needed .h/.hpp files in /usr/include/CXXGraph.

**Comment by nrkramer** [comment] 2023-05-06 07:13
Opened up a new PR to address this here: https://github.com/ZigRazor/CXXGraph/pull/276

**Closed** 2023-05-07 17:06 UTC
Labels: enhancement, good first issue, development, repo, Priority:High, hacktoberfest
